FILENAME REFFILE '/folders/myfolders/data-table-B1.XLS';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLS
	OUT=WORK.IMPORT;
	GETNAMES=YES;
RUN;

DATA FUTBOL;
SET IMPORT;
DROP X1 X2 X3 X4 X5 X6 X7 X9;
RUN;

PROC PRINT DATA=FUTBOL;RUN;

PROC REG DATA=FUTBOL;
MODEL Y=X8;
RUN;